// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PizzaProject.Data;

#nullable disable

namespace PizzaProject.Migrations
{
    [DbContext(typeof(PizzaProjectContext))]
    [Migration("20230303025429_p1")]
    partial class p1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PizzaProject.Models.Order", b =>
                {
                    b.Property<int>("orderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("orderId"));

                    b.Property<string>("add_flavour")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("no_of_pizza")
                        .HasColumnType("int");

                    b.Property<DateTime>("orderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("pizzaId")
                        .HasColumnType("int");

                    b.Property<string>("style")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("total_amount")
                        .HasColumnType("int");

                    b.HasKey("orderId");

                    b.HasIndex("pizzaId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("PizzaProject.Models.Pizza", b =>
                {
                    b.Property<int>("pizzaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("pizzaId"));

                    b.Property<string>("crust")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("no_of_slices")
                        .HasColumnType("int");

                    b.Property<string>("pizzaName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("price")
                        .HasColumnType("int");

                    b.Property<string>("size")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("speciality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("pizzaId");

                    b.ToTable("Pizza");
                });

            modelBuilder.Entity("PizzaProject.Models.Status", b =>
                {
                    b.Property<int>("statusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("statusId"));

                    b.Property<int>("orderId")
                        .HasColumnType("int");

                    b.Property<string>("status_details")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("statusId");

                    b.HasIndex("orderId");

                    b.ToTable("Status");
                });

            modelBuilder.Entity("PizzaProject.Models.Order", b =>
                {
                    b.HasOne("PizzaProject.Models.Pizza", "Pizza")
                        .WithMany("Orders")
                        .HasForeignKey("pizzaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pizza");
                });

            modelBuilder.Entity("PizzaProject.Models.Status", b =>
                {
                    b.HasOne("PizzaProject.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("orderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("PizzaProject.Models.Pizza", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
